### ISSUE TITLE
Problem with goloang-test-api

### ISSUE THREAD

**Issue by mstudham** [WeDias/golang-test-api#1]
Looks great, installed, server running, but  when I try the first Curl API I get 
{"error":"ERROR: relation \"product\" does not exist (SQLSTATE 42P01)"}%      
Any thoughts?   
![image](https://user-images.githubusercontent.com/9357346/180645978-df54a993-69a8-4532-90ca-e556606114f7.png)

**Comment by WeDias** [comment]
did you install via docker or manual?
if it was manual you need to run this [SQL](https://github.com/WeDias/golang-test-api/blob/main/resources/ddl-database.sql) in your Postgres :)
